language: python
python:
  - "2.7"
  - "3.6"
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - coverage run --source=cantools setup.py test
  - make test-sdist
  - env PYTHONPATH=. python examples/hello_world.py
  - env PYTHONPATH=. python examples/diagnostics/did.py
  - make test-c
  - make test-c-gcc-8
after_success:
  coveralls
